
import { AgentConfig, FileMap } from './types';

export function generatePythonProject(agent: AgentConfig): FileMap {
    const fileMap: FileMap = {};

    const name = agent.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
    const dir = `${name}-voice-agent-python`;

    // Resolve effective VAD values (agent config → Section 15 defaults)
    const vad = agent.config.vad;
    const vadThreshold = vad?.threshold ?? 0.85;
    const vadMinSpeechMs = vad?.min_speech_duration_ms ?? 250;
    const vadMinSilenceMs = vad?.min_silence_duration_ms ?? vad?.silence_timeout_ms ?? 500;
    const vadSpeechPadMs = vad?.speech_pad_ms ?? 300;
    const vadBargeInMinMs = vad?.barge_in_min_duration_ms ?? 300;
    const vadNoiseCancellation = vad?.noise_cancellation ?? true;
    const vadAllowBargeIn = vad?.barge_in ?? true;

    // Resolve effective STT values
    const sttOpts = agent.config.stt?.options ?? {};
    const sttEndpointing = sttOpts.endpointing ?? 400;
    const sttSmartFormat = sttOpts.smart_format ?? true;
    const sttPunctuate = sttOpts.punctuate ?? true;
    const sttNoDelay = sttOpts.no_delay ?? true;

    // Resolve input validation values
    const iv = agent.config.input_validation;
    const ivEnabled = iv?.enabled ?? true;
    const ivMinWordCount = iv?.min_word_count ?? 2;
    const ivMinDurationMs = iv?.min_duration_ms ?? 1500;
    const ivMaxConsecutive = iv?.max_consecutive_invalid ?? 5;
    const ivEscalationThreshold = iv?.escalation_threshold ?? 3;
    const ivFillerWords = iv?.filler_words ?? ['uh', 'um', 'hmm', 'hm', 'ah', 'er', 'uhh', 'umm', 'mmm', 'oh'];

    // --- requirements.txt ---
    fileMap[`${dir}/requirements.txt`] = `livekit-agents>=1.0.0
python-dotenv>=1.0.0
livekit-plugins-silero>=1.0.0
${agent.config.stt?.provider === 'deepgram' ? 'livekit-plugins-deepgram>=1.0.0  # STT Provider' : ''}
${agent.config.stt?.provider === 'openai' ? 'livekit-plugins-openai>=1.0.0' : ''}
${agent.config.llm?.provider === 'openai' ? 'livekit-plugins-openai>=1.0.0' : ''}
${agent.config.llm?.provider === 'gemini' ? 'livekit-plugins-google>=1.0.0  # LLM Provider' : ''}
${agent.config.tts?.provider === 'cartesia' ? 'livekit-plugins-cartesia>=1.0.0  # TTS Provider' : ''}
${agent.config.tts?.provider === 'openai' ? 'livekit-plugins-openai>=1.0.0' : ''}
httpx>=0.27.0
`;

    // --- .env.example ---
    fileMap[`${dir}/.env.example`] = `LIVEKIT_URL=wss://your-project.livekit.cloud
LIVEKIT_API_KEY=
LIVEKIT_API_SECRET=

# Providers
${agent.config.stt?.provider?.toUpperCase()}_API_KEY=
${agent.config.llm?.provider?.toUpperCase()}_API_KEY=
${agent.config.tts?.provider?.toUpperCase()}_API_KEY=
`;

    // --- README.md ---
    fileMap[`${dir}/README.md`] = `# ${agent.name} — Voice Agent (Python)
Generated by VoiceAgent Builder.

## Configuration at a glance
- Language: ${agent.config.language}
- LLM: ${agent.config.llm?.provider} (${agent.config.llm?.model})
- STT: ${agent.config.stt?.provider} (${agent.config.stt?.model})
- TTS: ${agent.config.tts?.provider} (${agent.config.tts?.model})
- VAD threshold: ${vadThreshold} (noise rejection level)
- Barge-in: ${vadAllowBargeIn ? 'enabled' : 'disabled'} (${vadBargeInMinMs}ms gate)

## Quick start
1. Create virtual environment
   \`python -m venv venv && source venv/bin/activate\`

2. Install dependencies
   \`pip install -r requirements.txt\`

3. Set environment variables
   \`cp .env.example .env\`
   Open .env and fill in your API keys.

4. Run in development
   \`python agent/voice_agent.py dev\`

## VAD Tuning
Edit \`config/agent_config.py\` to tune noise sensitivity:
- Raise \`threshold\` if background noise triggers false interruptions (max 1.0)
- Lower \`threshold\` if the agent misses real speech (min 0.5)
- Raise \`min_silence_duration_ms\` if the agent cuts users off mid-sentence
- Raise \`barge_in_min_duration_ms\` if noise interrupts the agent while speaking
`;

    // --- config/agent_config.py ---
    fileMap[`${dir}/config/agent_config.py`] = `
from dataclasses import dataclass, field
from typing import List

@dataclass
class LLMConfig:
    provider: str = "${agent.config.llm?.provider}"
    model: str = "${agent.config.llm?.model}"
    options: dict = field(default_factory=lambda: ${JSON.stringify(agent.config.llm?.options || {})})

@dataclass
class STTConfig:
    provider: str = "${agent.config.stt?.provider}"
    model: str = "${agent.config.stt?.model}"
    # endpointing: ms after end-of-speech energy before STT finalises transcript.
    # Do NOT set utterance_end_ms — it causes multi-second listening delays.
    endpointing: int = ${sttEndpointing}
    smart_format: bool = ${sttSmartFormat ? 'True' : 'False'}
    punctuate: bool = ${sttPunctuate ? 'True' : 'False'}
    no_delay: bool = ${sttNoDelay ? 'True' : 'False'}  # Reduces Deepgram internal buffering latency.

@dataclass
class TTSConfig:
    provider: str = "${agent.config.tts?.provider}"
    model: str = "${agent.config.tts?.model}"
    voice: str = "${agent.config.tts?.voice}"
    speed: str = "${agent.config.tts?.speed || 'normal'}"

@dataclass
class VADConfig:
    # threshold: 0.0–1.0. Higher = less sensitive.
    # Raise if background noise triggers false interruptions. Lower if agent misses real speech.
    threshold: float = ${vadThreshold}

    # Minimum ms of continuous speech before treating as real utterance.
    # Raise if short sounds (door slams, keyboard clicks) trigger false positives.
    min_speech_duration_ms: int = ${vadMinSpeechMs}

    # How long to wait after speech ends before closing utterance.
    # Raise if agent cuts user off mid-sentence during natural pauses.
    min_silence_duration_ms: int = ${vadMinSilenceMs}

    # Audio buffer added before detected speech onset.
    # Prevents the first syllable from being clipped.
    speech_pad_ms: int = ${vadSpeechPadMs}

    # Whether user can interrupt agent while it is speaking.
    allow_barge_in: bool = ${vadAllowBargeIn ? 'True' : 'False'}

    # Minimum ms of user speech before interrupting agent.
    # Raise if noise triggers false barge-ins.
    barge_in_min_duration_ms: int = ${vadBargeInMinMs}

    # Enable noise cancellation before VAD and STT.
    # Disable if you experience audio quality issues.
    noise_cancellation: bool = ${vadNoiseCancellation ? 'True' : 'False'}

@dataclass
class InputValidationConfig:
    enabled: bool = ${ivEnabled ? 'True' : 'False'}
    # Utterances with fewer real words than this are flagged as too_short.
    min_word_count: int = ${ivMinWordCount}
    # Short utterances below this duration (ms) are also flagged as too_short.
    min_duration_ms: int = ${ivMinDurationMs}
    # STT confidence below this triggers a clarification request.
    confidence_threshold: float = 0.75
    # Consecutive invalids of same type before escalation phrase.
    escalation_threshold: int = ${ivEscalationThreshold}
    # Total consecutive invalids before falling through to silence handling.
    max_consecutive_invalid: int = ${ivMaxConsecutive}
    filler_words: List[str] = field(default_factory=lambda: ${JSON.stringify(ivFillerWords)})

@dataclass
class AgentConfig:
    name: str = "${agent.name}"
    language: str = "${agent.config.language}"
    llm: LLMConfig = field(default_factory=LLMConfig)
    stt: STTConfig = field(default_factory=STTConfig)
    tts: TTSConfig = field(default_factory=TTSConfig)
    vad: VADConfig = field(default_factory=VADConfig)
    input_validation: InputValidationConfig = field(default_factory=InputValidationConfig)

AGENT_CONFIG = AgentConfig()
`;

    // --- config/workflow_steps.py ---
    const stepsPy = (agent.config.workflow_steps || []).map(s => ({
        name: s.name,
        description: s.description,
        prompt_addition: s.prompt_addition
    }));

    fileMap[`${dir}/config/workflow_steps.py`] = `
WORKFLOW_STEPS = ${JSON.stringify(stepsPy, null, 4)}
`;

    // --- config/system_prompt.py ---
    fileMap[`${dir}/config/system_prompt.py`] = `
def build_system_prompt(current_step_index: int, current_step_name: str, total_steps: int, step_prompt_addition: str) -> str:
    base_prompt = """${agent.config.system_prompt}"""

    return f"""{base_prompt}

{step_prompt_addition}

--- BEHAVIOR RULES ---
1. You are on step {current_step_index + 1} of {total_steps}: {current_step_name}.
2. Only confirm actions when a tool returns success.
3. If unsure, ask clarifying questions.
4. Keep responses to 1-3 sentences. Do not use lists or bullet points.
"""
`;

    // --- agent/input_validator.py ---
    fileMap[`${dir}/agent/input_validator.py`] = `"""
input_validator.py
Pre-LLM utterance gate. Validates every user transcript before it is
forwarded to the language model. Filters noise, filler words, and
low-confidence captures. Rotates clarification phrases so the agent
never sounds robotic, and escalates after repeated failures.
"""

from config.agent_config import AGENT_CONFIG

TOO_SHORT_PHRASES = [
    "Sorry, I didn't quite catch that. Could you say that again?",
    "I'm not sure I heard you fully. Could you repeat that?",
    "Pardon? I didn't quite get that.",
]

LOW_CONFIDENCE_PHRASES = [
    "Sorry, I didn't quite get that. Could you say that a bit more clearly?",
    "I'm having a little trouble hearing you. Could you repeat that?",
    "Could you say that again? I want to make sure I understood correctly.",
]

ESCALATION_PHRASE = (
    "I'm really sorry, I'm having trouble understanding. "
    "Could you try speaking a little closer to your microphone?"
)

FILLER_WORDS = set(AGENT_CONFIG.input_validation.filler_words)


class InputValidator:
    def __init__(self):
        self._counters = {"empty": 0, "filler_only": 0, "too_short": 0, "low_confidence": 0}
        self._rotation = {"empty": 0, "filler_only": 0, "too_short": 0, "low_confidence": 0}
        self._total_consecutive = 0

    def validate(self, transcript: str, confidence: float, duration_ms: float) -> tuple[bool, str | None]:
        """
        Returns (is_valid, reason_if_invalid).
        reason is one of: 'empty', 'filler_only', 'too_short', 'low_confidence', or None.
        """
        cfg = AGENT_CONFIG.input_validation
        trimmed = transcript.strip()

        if not trimmed:
            return False, "empty"

        words = trimmed.lower().split()

        if all(w in FILLER_WORDS for w in words):
            return False, "filler_only"

        meaningful = [w for w in words if w not in FILLER_WORDS]
        if len(meaningful) < cfg.min_word_count and duration_ms < cfg.min_duration_ms:
            return False, "too_short"

        if confidence < cfg.confidence_threshold:
            return False, "low_confidence"

        # All checks passed — reset counters
        self._total_consecutive = 0
        for k in self._counters:
            self._counters[k] = 0

        return True, None

    def get_clarification_phrase(self, reason: str) -> str | None:
        """
        Returns the phrase to speak, or None if the agent should stay silent.
        """
        cfg = AGENT_CONFIG.input_validation

        if reason in ("empty", "filler_only"):
            return None

        self._counters[reason] += 1
        self._total_consecutive += 1

        if self._total_consecutive >= cfg.max_consecutive_invalid:
            return None

        if self._counters[reason] >= cfg.escalation_threshold:
            return ESCALATION_PHRASE

        phrases = TOO_SHORT_PHRASES if reason == "too_short" else LOW_CONFIDENCE_PHRASES
        idx = self._rotation[reason] % len(phrases)
        self._rotation[reason] += 1
        return phrases[idx]

    def reset(self):
        self._total_consecutive = 0
        for k in self._counters:
            self._counters[k] = 0
            self._rotation[k] = 0
`;

    // --- agent/voice_agent.py ---
    const sttInit = agent.config.stt?.provider === 'deepgram'
        ? `deepgram.STT(
        model=AGENT_CONFIG.stt.model,
        # endpointing: ms after end-of-speech before STT finalises transcript.
        # Do NOT set utterance_end_ms — it causes multi-second listening delays.
        endpointing=AGENT_CONFIG.stt.endpointing,
        smart_format=AGENT_CONFIG.stt.smart_format,
        punctuate=AGENT_CONFIG.stt.punctuate,
        no_delay=AGENT_CONFIG.stt.no_delay,
    )`
        : `openai.STT()`;

    const llmInit = agent.config.llm?.provider === 'gemini'
        ? `google.LLM(model=AGENT_CONFIG.llm.model)`
        : `openai.LLM(model=AGENT_CONFIG.llm.model)`;

    const ttsInit = agent.config.tts?.provider === 'cartesia'
        ? `cartesia.TTS(voice=AGENT_CONFIG.tts.voice)`
        : `openai.TTS(voice=AGENT_CONFIG.tts.voice)`;

    const pluginImports = [
        agent.config.stt?.provider === 'deepgram' ? 'from livekit.plugins import deepgram' : '',
        agent.config.stt?.provider === 'openai' || agent.config.llm?.provider === 'openai' || agent.config.tts?.provider === 'openai'
            ? 'from livekit.plugins import openai' : '',
        agent.config.llm?.provider === 'gemini' ? 'from livekit.plugins import google' : '',
        agent.config.tts?.provider === 'cartesia' ? 'from livekit.plugins import cartesia' : '',
    ].filter(Boolean).join('\n');

    fileMap[`${dir}/agent/voice_agent.py`] = `"""
voice_agent.py
Main agent entry point. Initialises VAD, STT, LLM, TTS with tuned parameters,
applies barge-in noise gate, and runs pre-LLM input validation on every utterance.
"""

import asyncio
import logging
import time
from livekit.agents import AutoSubscribe, JobContext, WorkerOptions, cli, voice
from livekit.plugins import silero
${pluginImports}
from config.agent_config import AGENT_CONFIG
from config.system_prompt import build_system_prompt
from config.workflow_steps import WORKFLOW_STEPS
from agent.input_validator import InputValidator
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)


async def entrypoint(ctx: JobContext):
    await ctx.connect(auto_subscribe=AutoSubscribe.AUDIO_ONLY)
    logger.info(f"[AGENT] Connected to room: {ctx.room.name}")

    # ── STT ──────────────────────────────────────────────────────────────────
    stt_plugin = ${sttInit}

    # ── LLM ──────────────────────────────────────────────────────────────────
    llm_plugin = ${llmInit}

    # ── TTS ──────────────────────────────────────────────────────────────────
    tts_plugin = ${ttsInit}

    # ── VAD ──────────────────────────────────────────────────────────────────
    # threshold: ${vadThreshold} — requires ${Math.round(vadThreshold * 100)}% confidence it's human voice.
    #   Filters keyboard clicks, AC hum, notification sounds (typically score < 0.5).
    # min_speech_duration: ${vadMinSpeechMs}ms — ignores transient sounds (door slams < 100ms).
    # min_silence_duration: ${vadMinSilenceMs}ms — waits after speech ends before closing utterance.
    # pre_speech_pad_duration: ${vadSpeechPadMs}ms — buffers audio before onset so first syllable is never clipped.
    vad_plugin = silero.VAD.load(
        min_silence_duration=AGENT_CONFIG.vad.min_silence_duration_ms / 1000,
        min_speech_duration=AGENT_CONFIG.vad.min_speech_duration_ms / 1000,
        pre_speech_pad_duration=AGENT_CONFIG.vad.speech_pad_ms / 1000,
        positive_speech_threshold=AGENT_CONFIG.vad.threshold,
        negative_speech_threshold=max(AGENT_CONFIG.vad.threshold - 0.15, 0.5),
    )

    system_prompt = build_system_prompt(
        0,
        WORKFLOW_STEPS[0]["name"] if WORKFLOW_STEPS else "Start",
        len(WORKFLOW_STEPS),
        WORKFLOW_STEPS[0].get("prompt_addition", "") if WORKFLOW_STEPS else "",
    )

    # ── Input Validator (pre-LLM gate) ───────────────────────────────────────
    validator = InputValidator()

    agent = voice.Agent(
        vad=vad_plugin,
        stt=stt_plugin,
        llm=llm_plugin,
        tts=tts_plugin,
        instructions=system_prompt,
    )

    session = voice.AgentSession(
        vad=vad_plugin,
        stt=stt_plugin,
        llm=llm_plugin,
        tts=tts_plugin,
    )

    # ── Barge-in noise gate ───────────────────────────────────────────────────
    # Requires ${vadBargeInMinMs}ms of sustained speech before interrupting agent.
    # Prevents keyboard clicks and notification sounds from cutting off the agent.
    speech_onset_time: float | None = None
    barge_in_min_s = AGENT_CONFIG.vad.barge_in_min_duration_ms / 1000

    @session.on("user_started_speaking")
    def on_user_started_speaking():
        nonlocal speech_onset_time
        speech_onset_time = time.monotonic()

    @session.on("user_stopped_speaking")
    def on_user_stopped_speaking():
        nonlocal speech_onset_time
        if speech_onset_time is not None:
            duration = time.monotonic() - speech_onset_time
            if duration < barge_in_min_s:
                logger.info(
                    f"[BARGE-IN] ⚡ Short audio event ({duration * 1000:.0f}ms < "
                    f"{AGENT_CONFIG.vad.barge_in_min_duration_ms}ms) — suppressed."
                )
            speech_onset_time = None

    # ── Pre-LLM input validation ──────────────────────────────────────────────
    @session.on("user_speech_committed")
    async def on_user_speech_committed(event):
        if not AGENT_CONFIG.input_validation.enabled:
            return

        transcript = getattr(event, "transcript", "") or getattr(event, "text", "")
        confidence = getattr(event, "confidence", 1.0)
        duration_ms = getattr(event, "duration_ms", 2000)

        is_valid, reason = validator.validate(transcript, confidence, duration_ms)

        if not is_valid and reason:
            phrase = validator.get_clarification_phrase(reason)
            logger.info(f'[VALIDATOR] ❌ Invalid ({reason}): "{transcript[:60]}"')

            if phrase:
                try:
                    await session.say(phrase, allow_interruptions=False)
                except Exception as e:
                    logger.error(f"[VALIDATOR] Failed to speak clarification: {e}")

            if hasattr(event, "prevent_default"):
                event.prevent_default()
            return

        logger.info(f'[VALIDATOR] ✅ Valid: "{transcript[:60]}"')

    await session.start(agent=agent, room=ctx.room)
    logger.info("[AGENT] 🎙️  Agent is live and listening!")
    logger.info(
        f"[AGENT] VAD: threshold={AGENT_CONFIG.vad.threshold}, "
        f"minSpeech={AGENT_CONFIG.vad.min_speech_duration_ms}ms, "
        f"minSilence={AGENT_CONFIG.vad.min_silence_duration_ms}ms"
    )


if __name__ == "__main__":
    cli.run_app(WorkerOptions(entrypoint_fnc=entrypoint))
`;

    return fileMap;
}
